### ISSUE TITLE
Build and Test AIDE Database | Incorrect for ubuntu profiles on ansible snippet

### ISSUE THREAD

**Issue by samwozencroft** [OpenSCAP/openscap-report#136]
Current block is:

- name: Build and Test AIDE Database
  command: /usr/sbin/aide --init
  changed_when: true
  when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
  - CJIS-5.10.1.3
  - NIST-800-53-CM-6(a)
  - PCI-DSS-Req-11.5
  - aide_build_database
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy
  
  Correct block should be:
  
  - name: Build and Test AIDE Database
  command: /usr/bin/aide --init
  changed_when: true
  when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  tags:
  - CJIS-5.10.1.3
  - NIST-800-53-CM-6(a)
  - PCI-DSS-Req-11.5
  - aide_build_database
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - restrict_strategy

**Comment by Honny1** [comment]
Hello @samwozencroft,
thank you for creating the issue. I tried to reproduce the problem. And I found that this problem you mention is a content problem. Please create an issue [here](https://github.com/ComplianceAsCode/content/issues).
